[package]
name = "backtracking"
version = "0.1.0"
authors = ["lcnr/Bastian Kauschke <bastian_kauschke@hotmail.de>"]
edition = "2018"

[dependencies]
primal-bit = "0.2.4"
rand = "0.7"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "bench"
harness = false